### PR TITLE
Fix issue where network call was done on screen rotation

### LINKED ISSUE #152: Error after registration and screen gets rotated
```
04-25 15:52:05.048 29235-29235/com.tvnu.app D/SCHACC: Request to POST https://identity-pre.schibsted.com/api/2/signup failed with code 302. 
    Type: <ApiException> 
    Description: <, >
```

See: https://sch-chat.slack.com/files/U0DT8KR55/FAE7T1SP6/device-2018-04-27-125824.webm

### PR DESCRIPTION
**Pull request by Astach**
Fixes #152

### CODE REVIEW

File: core/src/main/java/com/schibsted/account/engine/step/StepSignUpDone.kt [hunk 1]
```diff
@@ -0,0 +1,25 @@
+package com.schibsted.account.engine.step
+
+import android.os.Parcel
+import android.os.Parcelable
+import com.schibsted.account.engine.input.Identifier
+
+class StepSignUpDone(val identifier: Identifier) : Step(), Parcelable {
```
Comment (Nexcius) [inline core/src/main/java/com/schibsted/account/engine/step/StepSignUpDone.kt]: This is not needed, please remove
