### PR TITLE
Fix issue where user was not logged in after a successful deeplink signup redirection

### LINKED ISSUE #62: Fails to log the user in after successful deep link redirection
When trying to parse the deeplink there's a check :
` it -> it.host == null && it.path.startsWith("/login") || it.host == "login" }` but in somes cases ( like Aftenposten) the path is "/login" and the host is not null (it's "spid") ` it.host == null ` has to be removed from the check

### PR DESCRIPTION
**Pull request by Astach**
Fixes #62

### CODE REVIEW

File: core/src/main/java/com/schibsted/account/util/DeepLinkHandler.kt [hunk 1]
```diff
@@ -26,7 +26,7 @@ object DeepLinkHandler {
         val uri: URI? = Try { URI.create(dataString) }.getOrElse {
             Logger.info(TAG, { "Unable to parse deep link: ${dataString.safeUrl()}" }, it)
             null
-        }?.takeIf { it -> it.host == null && it.path.startsWith("/login") || it.host == "login" }
+        }?.takeIf { it -> it.path.startsWith("/login") || it.host == "login" }
```
Comment (Nexcius) [inline core/src/main/java/com/schibsted/account/util/DeepLinkHandler.kt]: We need to be restrictive with this. Add the case instead :1313:
